sonar.projectKey=ferreteria-kanos_backend
sonar.organization=ferreteria-kanos

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Backend
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src/main
sonar.tests=src/test

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Provide compiled classes to Sonar
sonar.java.binaries=target/classes

# Tell SonarCloud where the JaCoCo XML report is located
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions to pass Quality Gate
sonar.cpd.exclusions=**/dto/**/*,**/entity/**/*
sonar.coverage.exclusions=**/controller/**/*,**/service/**/*,**/services/**/*,**/dto/**/*,**/entity/**/*,**/config/**/*,**/security/**/*,**/*Exception.java,**/MasterApplication.java
