server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TU_BASE_DE_DATOS # Cambiar por la base de datos real
    username: TU_USUARIO # Cambiar por el usuario real
    password: TU_PASSWORD # Cambiar por el password real
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
